services:
  db:
    image: postgres:16-alpine
    container_name: virtuo-db
    restart: always
    environment:
      POSTGRES_USER: virtuo
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: virtuo
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: virtuo-backend
    restart: always
    environment:
      DATABASE_URL: "postgresql://virtuo:yourpassword@db:5432/virtuo?schema=public"
      JWT_SECRET: "virtuo-super-secret-key-12345"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: virtuo-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend